### ISSUE TITLE
Создайте один общий style.scss

### ISSUE THREAD

**Issue by yuchiko** [rudnichenko/Fitness-landing-page#1]
Вам же будет проще, если у вас будет файлик куда вы импортите все остальные. 
Так и структура зрительно ясна и не нужно будет каждый раз `@import "variables";` в начале всех файлов стилей вставлять.

Пример общего файла стилей [style.scss](https://github.com/yuchiko/wp-gulp-starter-kit/blob/master/assets/scss/style.scss)

Не забывайте, что файл стиля, который в дальнейшем будет импортирован нужно называть со знаком `_` перед названием. Так мы показываем, что файл составляющий другого и компилировать его в отдельный css не нужно.
Например: `_introduction-promo.scss`

**Comment by esperanzzza** [comment]
Спасибо, опять-таки я именно так я в less и делала. А когда по той же схеме сделала c sass, создала файлик styles.scss, с sass gulp начал выдавать ошибку, что неизвестные переменные, если их не подключать в начале файлв через директиву import.
