### ISSUE TITLE
& и БЭМ

### ISSUE THREAD

**Issue by yuchiko** [rudnichenko/Fitness-landing-page#2]
Элементы и модификаторы обязательно нужно создавать с помощью `&`
Пример с этого файла `introduction-promo.scss`

Тут 👍 , что файл называется как и имя блока, но потом идёт ошибка, что не используете nesting правильно

```
.introduction-promo {

	&__slogan {}

	&__slogan-heading {}

	&__slogan-heading--line {}

	&__slogan-text{}
	
	&__slogan-text--line{}
}
```

**Comment by esperanzzza** [comment]
Да, это я тоже знаю, именно так я по less и делала. Мне вообще sass не нравится, не удобно( Но прикол в том, что когда я так верстаю по sass, у меня выдается ошибка. Где-то надо разобраться. А & только с псевдоэлементами хорошо пока работает.
