### ISSUE TITLE
gulp watchers ?

### ISSUE THREAD

**Issue by yuchiko** [rudnichenko/Fitness-landing-page#6]
Так долго читали про gulp, а одну из самых крутых фич не заюзали? 
Обязательно добавьте gulp.watch таску

**Comment by esperanzzza** [comment]
Я добавила только gulp sass пока, т.к. это нужно было хотя бы для начала работы. Естественно, и watch нужен, и browser synch нужен, и минимизаторы и т.д. Там много тасков еще добавить обязательно нужно
